### ISSUE TITLE
Error al importar el grafo a unity

### ISSUE THREAD

**Issue by JuanCamiloUsecheRodriguez** [VivianGomez/Tweenity#2]
Al correr la aplicación luego de importar el grafo se presentan estos errores:
![image](https://user-images.githubusercontent.com/20799482/139447117-187f98e2-30c2-417f-877e-ce60da1b9e78.png)

**Comment by VivianGomez** [comment]
Esto pasa porque se está incumpliendo alguna de las reglas de formato y no se logra _parsear_ tu grafo. Uno de los problemas posibles puede ser:
1. El nodo inicial no tiene el tag [START]
2. Los nodos random no tienen los ":"  o en la descripción hay ":"
3. en algún nodo no se siguió  la estructura base:

```
En la sección descriptiva no se debe usar ":" 
<img src="url de github o drive con el boceto" width="500" height="300">
@
[[Nombre del nodo hijo, siguiendo la instrucción #1 sobre el nombramiento. Ej: _Tomar el rodillo para aplanar la masa_]]
{
masa.seleccionar()
}
<
simulador.esperar(1)
controladorReceta.mostrarSarten()
controladorReceta.mostrarRodillo()
> 
```

Para ayudarte a encontrar el error, por favor sube acá el grafo en html y el txt "proofing format"

**Comment by JuanCamiloUsecheRodriguez** [comment]
Hola Vivian, gracias por tu pronta respuesta. Revise los errores que comentaste pero no encuentro que sea ninguno de ellos.
[entweed1635465741179.txt](https://github.com/VivianGomez/Tweenity/files/7442562/entweed1635465741179.txt)
github no soporta el archivo html, te lo enviare al correo

**Comment by VivianGomez** [comment]
Gracias a ti por informar tus dudas.
Bueno, para hacer debug de tu grafo lo que hice fue ir al script _SimulationObject.cs_ y descomentar las líneas "Debug.Log(..." para poder imprimir el resultado del _parser_.
Lo que pude encontrar es que tienes una acción de usuario que no tiene un formato correcto en los parámetros:
![image](https://user-images.githubusercontent.com/30846540/139452180-a78be51a-4993-47cb-b8a9-ec759e894a4c.png)

Adicionalmente, si no es un nodo multipleChoice no deben haber 2 acciones de usuario, sólo una.
Es decir, en tu caso, como es un reminder, la primera linea en {} es el recordatorio y la segunda la acciónde usuario esperada.

Por otro lado, revisa que la manera en que escribes los tags sea la misma propuesta en la guia, por ejemplo "multipleChoice" y no "multiplechoice"

Quedo atenta!!!

**Comment by JuanCamiloUsecheRodriguez** [comment]
Hola Vivian, corregimos los posibles errores que nos comentaste pero sigue sin funcionar. El primer error cambio en su descripción pero el segundo sigue igual
[entweed1635518658278.txt](https://github.com/VivianGomez/Tweenity/files/7442958/entweed1635518658278.txt)
.

**Comment by JuanCamiloUsecheRodriguez** [comment]
![image](https://user-images.githubusercontent.com/20799482/139459346-278b6c05-212e-45f0-828a-f3f2b155df48.png)
estos son los errores luego de las correciones

**Comment by VivianGomez** [comment]
Si, el error va a ser el mismo hasta que todos los nodos tengan bien el formato.

Si quieres saber dónde está el error (nodo), entra al script SimulationObject.cs y descomentar las líneas "Debug.Log(..."
![image](https://user-images.githubusercontent.com/30846540/139460491-89ba90c6-cad8-4b01-b7dd-2dcab56e7baf.png)

Así me imprime cosas del tipo:
![image](https://user-images.githubusercontent.com/30846540/139460580-263bb002-652f-4ca0-9c4e-ca579ae238d1.png)

Y con eso podemos saber en cual nodo está el error, por ejemplo en el caso de esa imagen era en "Añadir especias...", luego vamos al txt y miramos si tenemos bien el formato.


Haciendo exactamente eso encuentro nuevos errores:
1. Te falta un arroba en este nodo:
![image](https://user-images.githubusercontent.com/30846540/139459974-c1f42e52-5683-4558-98f3-e85575a7ab3c.png)

En este:
![image](https://user-images.githubusercontent.com/30846540/139460353-7aad47d4-738d-4c7c-bd96-223c09b6f664.png)

Y en este:
![image](https://user-images.githubusercontent.com/30846540/139460427-904f7ae6-ebc3-46c1-91a4-f44e962e2010.png)


Corregí esos tres y ya sirve. 
Intentalo y me cuentas! :D

**Comment by JuanCamiloUsecheRodriguez** [comment]
Error comentado en clase sobre el segundo nodo del grafo.
[entweed1635525765677.txt](https://github.com/VivianGomez/Tweenity/files/7445007/entweed1635525765677.txt)
Descripción del error.
![image](https://user-images.githubusercontent.com/20799482/139504387-be360fcc-4338-4cc7-9f42-f4bbe7e4c92b.png)

**Comment by NicolasAbo17** [comment]
Hola estamos teniendo el mismo error. 
Es como si el codigo no pudiera encontrar '\r\n'

![image](https://user-images.githubusercontent.com/38436508/139949568-9a18a1f6-58df-466f-9936-ceb1c9017d9f.png)

**Comment by NicolasAbo17** [comment]
De hecho si uso el grafo de TutorialUsoTweenity para generar el texto ese texto también saca error. Importamos el formato Entwee tal como decía el tutorial, pero los archivos se están generando sin los items '\r\n'

**Comment by VivianGomez** [comment]
Hola Nicolás!

Podemos hacer dos cosas:
1. Asegúrate de estar copiando el contenido del txt y no usando el que se descarga. 
Es posible que ese sea tu error, porque por alguna razón no queda en UTF8 o una codificación que entienda Unity.

2. Haz el procedimiento de [debug que se muestra más arriba](https://github.com/VivianGomez/Tweenity/issues/2#issuecomment-954829574) y que hicimos en la última clase (viernes 29 de octubre), el video está en teams.
Y cuando lo tengas déjame ver que te imprime, así te puedo ayudar más.
