### ISSUE TITLE
Error en llamar anim.setBool() despues de exportar proyecto a .apk

### ISSUE THREAD

**Issue by sebascal1** [VivianGomez/Tweenity#4]
Cuando intento hacer el build de .apk del proyecto, el dialogue viewer no aparece y no se puede proceder dentro del simulador.  Al tratar correr la escena en playmode despues de haber hecho el build, consigo el siguiente error:
![LogHuertoVirtual](https://user-images.githubusercontent.com/60772784/139756433-9310e931-b09e-4d8c-b872-817a1361a417.PNG)

Haciendo el debug interno (los ultimos dos logs) se ilustra que el NullReference es debido a que no encuentra la variable anim referenciando el componente de animator. Asumo que es la misma razon por la cual no funciona el build de apk.

Antes de hacer el build de apk, el dialogueViewer actua sin problemas, al cerrar unity y abrir el proyecto de nuevo, tampoco tengo problemas.

**Comment by VivianGomez** [comment]
Buen día Sebastian.

Dejame ver el detalle del null. Le das click y el te muestra el detalle en líneas de código o te señala el objeto al que le hace falta la referencia. 
Esto para porque estas intentando acceder algo y no se lo diste, bien sea un gameobject o un script. Pero necesito más detalle del error para ayudarte.

**Comment by sebascal1** [comment]
Hola Vivian, gracias por tu respuesta. Aqui te mando el detalle del null
![CapturaNullReference](https://user-images.githubusercontent.com/60772784/139856823-de8481ed-d813-4764-a3c9-2fe6efa6714a.PNG)

El null reference esta apuntando al DialogueViewer a esta linea especifica en el codigo:
![CapturaCodigoLocation](https://user-images.githubusercontent.com/60772784/139857051-be8a6918-0822-4373-bd68-72a837a9dde9.PNG)

Que es donde el simulador usa la referencia al Animator para cerrar o abrir la caja de dialogo. Al hacer el build, por una razon no logra guardar la referencia al componente del animator. 

Trate de hacerlo de forma directa cambiando la variable de anim a 'This.GetComponent Animator ()"/"GetComponent  Animator ()" y funciona bien antes de hacer el build. Sin embargo, despues de hacer el build obtengo el siguiente comportamiento:

https://user-images.githubusercontent.com/60772784/139857686-bf58ef25-02a4-42e8-aaf6-5fe7638f8be8.mp4

El dialogue box aparece, pero sin el texto del nodo, solamente el de defecto. Tambien hacer click en el no hace nada. Tampoco recibo mensajes de error.

Al reiniciar el proyecto de Unity, todo funciona bien. Este comportamiento solo ocurre despues de haber hecho el build, y en el build que es exportado. Gracias de antemano.

**Comment by sebascal1** [comment]
Hola Vivian, logre hacer un avance en el problema. El null reference me parece que sucedia porque el simulador estaba tratando de ejecutar la animacion antes de que la variable de anim fuera asignada (que no deberia suceder ya que la asignacion de anim esta en el metodo de Start() que se supone que ocurre al inicio del programa). Cambiando el metodo de Start() a un Awake() en dialogueViewer.cs parece haber solucionado el problema por ahora, pero seguire investigando y probando.

**Comment by VivianGomez** [comment]
Hola Sebastián 
Está raro ese error. Lo primero que te pido que verifiques es si en el DialogueViewer tienes asignada la cámara principal en el componente canvas. Como veo que usas Oculus Quest, sería:
![image](https://user-images.githubusercontent.com/30846540/139946652-5073826e-55bf-43a9-ba7e-1c2eb2f21bab.png)

Eso para el error en el que no te está capturando la entrada de usuario (seleccionar una opción)
También asegúrate de que el SimulatorController fue asignado al componente DialogueViewer, pues así es que se cargan los textos.

Por otro lado, la solución del Awake tiene sentido en la asignación, porque el awake se ejecuta antes que Start (en el ciclo de vida de unity). Gracias por reportarlo, es raro que no me ha pasado a mi, de casualidad tu tienes Quest2? o tienes Quest 1?

Si persiste el error hacemos una llamada corta, pero sería mañana después de las 330. 
Quedo atenta!

**Comment by sebascal1** [comment]
Hola Vivian,

Gracias por tu respuesta. Si todo estaba bien asignado previamente, que es la razon que me parecia raro que no funcionara una vez hacia el build. El dispositivo que he usado es el Quest 2.

He intentado re hacer el build y parece que ya con el cambio de Start a Awake  se a solucionado el problema por ahora. De todas maneras cualquier cosa te aviso. 

Muchas gracias!

**Comment by VivianGomez** [comment]
Se modifica cambiando Start por Awake en DialogueViewer, para el caso de los Oculus Quest2 reportado por Sebastián
