### ISSUE TITLE
Como invocar un nodo especifico

### ISSUE THREAD

**Issue by NicolasAbo17** [VivianGomez/Tweenity#5]
Tenemos una duda y es que nos gustaría saber como podemos invocar por código un nodo. Queremos que twine invoque algo y cuando cierta situación por código ocurra pasar a un nodo especifico. Creemos que seria multipleChoice, pero no sabemos como implementar la invocación del nodo deseado, sin utilizar botones.

**Comment by VivianGomez** [comment]
Hola Nicolás!
Si, suena a que quieren usar un multipleChoice.
Te dejo un video con una explicación simple y un  'ejemplo de juguete':


https://user-images.githubusercontent.com/30846540/139966700-631707fe-ef13-437a-9385-b2c4c785a6a4.mp4


Además el video [PARTE 2 Uso de package TWEENITY](https://youtu.be/0qeRnHP2jz0?t=702) en el minuto en el que se explica como se debe modificar un gameObject para acceder a los métodos que se definen en el grafo y así detectar "cuando ocurre cierta situación" (acción de usuario) y el nodo al que se quiere pasar.
Les recomiendo que se vean el video completo, pues se explica de manera sencilla todos los tipos de nodos y el uso del paquete.

**Comment by NicolasAbo17** [comment]
Muchas gracias. Se me olvido escribirte, ya pudimos utilizar fácilmente las acciones de usuario muchas gracias!
