### ISSUE TITLE
error al importar grafo 

### ISSUE THREAD

**Issue by jm-olave** [VivianGomez/Tweenity#6]
hola vivian, al importar el grafo a unity nos sale el siguiente error 
![image](https://user-images.githubusercontent.com/60241569/140007357-bade5741-c2dd-4e22-9895-85e2f5a38afa.png)

**Comment by VivianGomez** [comment]
Hola J.
Necesito más información del error, sigue las instrucciones de Dedug de este issue https://github.com/VivianGomez/Tweenity/issues/2 en el que respondí varias dudas al importar. 
Cuando actives el debug, muéstrame que se imprime en consola antes del error. 
Parece que no es de lectura, sino que te hace falta la referencia a algún objeto, bien sea por las acciones de simulador o algún elemento que no has asociado al prefab de SimulatorController. Sin embargo, necesito más detalles para ayudarte más.

**Comment by VivianGomez** [comment]
Ya se cual es el error, recuerda que NO es descargar el _proofing format_  tal cual como se descarga de Twine, sino copiar su contenido en un txt que crees desde tu editor de texto, puesto que por alguna razón lo descarga con otra codificación que no lee unity.

Te envío un video replicando el error que creo que tienes y la solución descrita arriba.

https://user-images.githubusercontent.com/30846540/140060250-65685108-bd9a-4186-b034-122093dd837d.mp4

:

**Comment by jm-olave** [comment]
Hola, me sigue saliendo el mismo error, ya revise que el archivo de texto este en UTF-8, que otra razon podria ser?
Segun entiendo el codigo error me indica que simulationcontroller en el archivo LoggerGraph es null.
![image](https://user-images.githubusercontent.com/60241569/140195972-4d40af69-eee9-414e-9f3e-23b2bb1df67a.png)

**Comment by VivianGomez** [comment]
Si quieres nos reunimos y lo vemos en detalle

**Comment by VivianGomez** [comment]
Cuando nos reunimos con Joshua encontramos 3 errores de sintaxis:
1.  faltaba el tag START en el nodo inicial
2.  Un nodo tenía primero las acciones de usuario {} y luego los nodos hijo o posibles caminos [[]]. 
Sin embargo, el orden es el contrario, primero [[]] y luego {}
3. Un nodo de tipo _dialogue_ tenía en el texto a mostrar en el cuadro de diálogo el tag <img /> de html con su respectivo src, sin embargo, ahí no se esperan esos caracteres especiales <> y por lo tanto se generaba un error.
