### ISSUE TITLE
Grafo end

### ISSUE THREAD

**Issue by NicolasAbo17** [VivianGomez/Tweenity#7]
Hola Vivian buenos días. Te escribo porque no sabemos como hacer que el código del nodo END se ejecute. Para ver si nos podrías ayudar con eso. Porque llega a ese nodo pero no corre lo que hay dentro.
![image](https://user-images.githubusercontent.com/38436508/140382933-7966fc3e-8a23-4f73-880b-cec1c4995e9c.png)
![image](https://user-images.githubusercontent.com/38436508/140382963-e99fb8c9-36a7-43fc-8182-e5d5bbe26132.png)
Gracias de antemano

**Comment by VivianGomez** [comment]
Basta con tener el Tag END, así que necesito más detalle de lo que está ocurriendo en la lectura del grafo.
Me puedes mostrar el resultado de al menos las ultimas 10 líneas que imprime la consola?
Quiero saber si realmente está entrando al nodo después de tocar el botón exit.

**Comment by NicolasAbo17** [comment]
Si entra. En la consola lo muestra. Pero el código de su interior no se corre. Ya ahora te mando las screenshots

**Comment by VivianGomez** [comment]
Dale. De todos modos también te envié un correo para hacer una reunión por videollamada y ver en detalle el error.
Puedo desde ahorita hasta antes de las 5 y sería por teams.

**Comment by NicolasAbo17** [comment]
![image](https://user-images.githubusercontent.com/38436508/140416806-94cf7416-e77f-46b4-badb-a73fa1eea470.png)
Listo ya te contestó por teams

**Comment by VivianGomez** [comment]
Para todos: si basta con tener el tag END, lo que pasa es que el método que quería probar Nicolás, para cerrar la app, sólo se puede probar cuando genere el apk.
