### ISSUE TITLE
Error para detectar botones usando raycast cuando el simulationController está activado

### ISSUE THREAD

**Issue by JulianMendozaRuiz** [VivianGomez/Tweenity#9]
https://user-images.githubusercontent.com/46912858/140427912-f6dd7f33-9378-4568-885a-5e0c6ea59a38.mp4

https://user-images.githubusercontent.com/46912858/140427949-d8c410f3-861c-42df-b89a-3150b16ea2e2.mp4

Estamos intentando utilizar botones para activar ciertas acciones con Twinity pero no son detectadas mientras está activo el simulationController con el que ejecutamos el grafo. Cuando lo desactivamos los botones permiten seleccionarse sin problemas.

**Comment by VivianGomez** [comment]
Dejame ver qué gameobjects del prefab de simulation controler están usando
Por ejemplo, si tienen el dialogue, asegurense de no tener dos eventsystem y de tener el eventsystem que necesite el paquete de VR que estén usando
![image](https://user-images.githubusercontent.com/30846540/140433412-cbc4fe9d-45d5-412a-a59f-b61cc7169084.png)

**Comment by JulianMendozaRuiz** [comment]
Hola, efectivamente era eso. Muchas gracias
